### ISSUE TITLE
Create a `requirements.txt` to install dependencies

### ISSUE THREAD

**Issue by cmaureir** [Aens/Gw2RaidExplorer#1]
All the modules that are not Python standard should go on this file
to provide an easy way to install all the dependencies.

**Comment by Aens** [comment]
Yup, I see this everywhere, but I'm self-taughing myself programming and I yet have to figure out how to only add to requirements file the libraries this imports and not everything I have installed on that virtualenv or dependencies of the libraries I'm using for this. Any easy way to do that?

**Comment by LairdStreak** [comment]
pip freeze > requirements.txt FTW
