### ISSUE TITLE
Decide which License file to keep

### ISSUE THREAD

**Issue by cmaureir** [Aens/Gw2RaidExplorer#3]
At the moment there are two LICENSE files, `LICENSE` and `LICENSE.txt`, which one is the right one? if by any chance those are complementary, you should still keep them in one file.

**Comment by Aens** [comment]
Oops. I'm a noob at Licenses (this is my first project) and wasn't sure which one to use.

**Comment by Aens** [comment]
Should I keep all those licenses because I'm using all those technologies?
